server:
  port: 19080
  servlet:
    context-path: /customermanager
version: v1

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.1:3306/merchant?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: migu@1234
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 180000
      auto-commit: true
      pool-name: merchantpool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml

customermanager:
  auth:
    excludeurls: ${server.servlet.context-path}/${version}/healthcheck,${server.servlet.context-path}/${version}/customer/auth/login